seed: 42
output_dir: runs
data_root: ${ENV:DATA_ROOT}
splits_file: configs/splits.json
img_size: 300
batch_size: 16
num_workers: 4
balance_sampler: true
epochs: 25
lr: 3.0e-4
weight_decay: 1.0e-4
warmup_epochs: 1
backbone: resnet34
pretrained: true
pool: avg
num_classes: null
label_smoothing: 0.05
aug:
  random_resized_crop_scale: [0.8, 1.0]
  hflip_p: 0.5
  color_jitter: [0.1, 0.1, 0.1, 0.05]
  rand_erase_p: 0.15
save_best_metric: macro_f1
patience: 7
